name: app_v01
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Flutter SDK
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.6
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^8.0.0  # Cập nhật phiên bản
  flutter_launcher_icons: ^0.13.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_datepicker: ^20.3.60
  flutter_floating_bottom_bar: ^1.1.0

# Assets
flutter:
  assets:
    - assets/icon/
    - assets/.env
    - assets/login/
    - assets/images/

  uses-material-design: true  # This line is essential for material icons to work

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"    
